version: 0.0
os: linux
files:
  - source: /
    destination: /vol/vabusinesses.org/htdocs/
file_exists_behavior: OVERWRITE
permissions:
    - object: /vol/vabusinesses.org/htdocs/
      owner: ubuntu
      group: ubuntu
      mode: 775
      type:
       - directory
# "location" is resolved relative to the root of the revision
AfterInstall:
  - location: deploy/postdeploy.sh
