services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-5001}:80"
    volumes:
      - type: bind
        source: .
        target: /var/www/htdocs/
    container_name: vabusinesses
